export const FETCH_RECIPES = "FETCH_RECIPES";
export const LOAD_RECIPES = "LOAD_RECIPES";
export const CREATE_RECIPE = "CREATE_RECIPE";
export const EDIT_RECIPE = "EDIT_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const FILTER_RECIPE = "FILTER_RECIPE";
export const RESET_FILTER_RECIPE = "RESET_FILTER_RECIPE";
